In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [5]:
import matplotlib.pyplot as plt

In [18]:
f=pd.read_csv('C:\\Users\\bharadwaj YVRao\\Desktop\\skilling for engineering-ML\\Home.csv');
f.head()

0  2009  21  9  6  84  121  14264
0  1  2007   4  2  3  86  121  12032
1  2  2016  18  3  7  90  120  13560
2  3  2002  13  2  2  80  128  12029
3  4  2014  25  5  8  81  122  14157
4  5  2008  11  9  3  88  126  14287

In [19]:
f.columns=['serial','date','age','distance','store','lattitude','longitude','price']

In [20]:
#Normilize the given data
f=f.iloc[:,1:] #removes sequence in dataset
f.head()

date  age  distance  store  lattitude  longitude  price
0  2007    4         2      3         86        121  12032
1  2016   18         3      7         90        120  13560
2  2002   13         2      2         80        128  12029
3  2014   25         5      8         81        122  14157
4  2008   11         9      3         88        126  14287

In [29]:
df_norm=(f-f.mean())/f.std()
df_norm.head()

date       age  distance     store  lattitude  longitude     price
0 -0.350447 -1.318954 -0.930413 -0.609189   0.325211  -1.261125 -1.836255
1  1.298471 -0.083366 -0.617878  0.663413   1.590122  -1.576801 -0.339484
2 -1.266513 -0.524647 -0.930413 -0.927340  -1.572157   0.948607 -1.839193
3  0.932045  0.534428  0.007190  0.981564  -1.255929  -0.945449  0.245315
4 -0.167234 -0.701160  1.257326 -0.609189   0.957666   0.317255  0.372658

In [25]:
#convert label value
y_mean=f['price'].mean()
y_mean
#y_std=df['price'].std()

13906.567113422685

In [27]:
y_std=f['price'].std()
y_std

1020.8644724718125

In [28]:
#as we are predicting price it must not be negative ,so we use this function
def convert_label_valuee(pred):
    return(pred*y_std+y_mean)

#example input
print(convert_label_valuee(-1.836486))

12031.763801830815


In [31]:
#task 3 
#select features
x=df_norm.iloc[:,:6]
x.head()

date       age  distance     store  lattitude  longitude
0 -0.350447 -1.318954 -0.930413 -0.609189   0.325211  -1.261125
1  1.298471 -0.083366 -0.617878  0.663413   1.590122  -1.576801
2 -1.266513 -0.524647 -0.930413 -0.927340  -1.572157   0.948607
3  0.932045  0.534428  0.007190  0.981564  -1.255929  -0.945449
4 -0.167234 -0.701160  1.257326 -0.609189   0.957666   0.317255

In [32]:
#select labels(Target)
y=df_norm.iloc[:,-1]
y.head()

0   -1.836255
1   -0.339484
2   -1.839193
3    0.245315
4    0.372658
Name: price, dtype: float64

In [54]:
#convert those values from list to respective arrays
#features and labels values
x_arr=x.values
y_arr=y.values
y_arr

array([-1.83625463, -0.33948396, -1.83919332, ...,  0.19143862,
        0.39812619, -1.11333791])

In [43]:
#train and Test split 
X_train,X_test,y_train,y_test=train_test_split(x_arr,y_arr,test_size=0.75)
y_test

array([-0.79595983, -0.36397301, -1.05260506, ...,  0.78701229,
       -0.36201388, -1.81078602])

In [35]:
from sklearn.linear_model import LinearRegression

In [36]:
lin=LinearRegression()
lin.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [52]:
y_pr=lin.predict(X_test)
y_predict=convert_label_valuee(y_pr)
y_predict

array([13235.47479921, 13597.68564954, 12585.35720162, ...,
       14518.42214732, 12989.22483087, 12607.64993878])

In [50]:
#lets convert predicted values from float to numbers as seen in the first data
y_test=convert_label_valuee(y_test)
y_test

array([1.36603096e+10, 1.41199040e+10, 1.33872626e+10, ...,
       1.53444471e+10, 1.41219884e+10, 1.25806274e+10])

In [48]:
y_pr

array([1.41350497e+10, 1.28468713e+10, 1.49383861e+10, ...,
       1.43972036e+10, 1.40554143e+10, 1.26617666e+10])

In [55]:
from sklearn import metrics
print(metrics.mean_squared_error(y_pr,y_test))


2.1172226951402527e+20
